### ISSUE TITLE
Rename calculated fields to avoid ambiguity section may be breaking due to execution order, not naming problem

### ISSUE THREAD

**Issue by gitgithan** [ben-n93/SQL-tips-and-tricks#10]
In `Rename calculated fields to avoid ambiguity` section
```
INSERT INTO products (product, revenue)
VALUES 
    ('Shark', 100),
    ('Robot', 150),
    ('Alien', 90);

-- The window function will rank the 'Robot' product as 1 when it should be 3.
SELECT 
product
, CASE product WHEN 'Robot' THEN 0 ELSE revenue END AS revenue
, RANK() OVER (ORDER BY revenue DESC)
FROM products
;
```
The text is saying that naming was the cause of the ranking bug, which implies if we change column alias `revenue`, it should work to rank `Robot` product as 3.
.
For example, changing `revenue` to `updated_revenue`:
```
SELECT 
product
, CASE product WHEN 'Robot' THEN 0 ELSE revenue END AS updated_revenue
, RANK() OVER (ORDER BY updated_revenue DESC)
FROM products
;
```

However this breaks with `Error 42703 column "updated_revenue" does not exist`.

I believe the lesson here is not that alias name clashing can cause bugs, but that window functions cannot refer to columns created at the same query scope, and that the solution would involve something like a subquery. This scoping issue is the same thing that QUALIFY aims to give convenience to.

Working subquery to rank `Robot` as 3
```
WITH ranked_products AS (
    SELECT 
        product,
        CASE product WHEN 'Robot' THEN 0 ELSE revenue END AS adjusted_revenue
    FROM products
)
SELECT 
    product,
    adjusted_revenue,
    RANK() OVER (ORDER BY adjusted_revenue DESC) AS rank
FROM ranked_products;
``` 

---
**DDL**

```

CREATE TABLE products (
    product VARCHAR(50) NOT NULL,
    revenue INT NOT NULL
);

INSERT INTO products (product, revenue)
VALUES 
    ('Shark', 100),
    ('Robot', 150),
    ('Alien', 90);
```

**Comment by ben-nour** [comment]
Thanks for flagging. 

In Snowflake and MariaDB it definitely works:

```SQL
SELECT 
product
, CASE product WHEN 'Robot' THEN 0 ELSE revenue END AS updated_revenue
, RANK() OVER (ORDER BY updated_revenue DESC)
FROM products
;
```

However you're right, doesn't look like it works in other RDBMs.

Rather than use subquery you can do this:

``` SQL
SELECT 
product
, CASE product WHEN 'Robot' THEN 0 ELSE revenue END AS updated_revenue
, RANK() OVER (ORDER BY CASE product WHEN 'Robot' THEN 0 ELSE revenue END DESC)
FROM products
;
```

I'll update the README, thanks!
