### ISSUE TITLE
Request adding which engines support which non-standard feature

### ISSUE THREAD

**Issue by gitgithan** [ben-n93/SQL-tips-and-tricks#11]
Would benefit readers to mention QUALIFY is not ansi standard and which engines have it. 
The post mentioned Snowflake once so i'm guessing that's where? 
Even if this post was based on Snowflake, good to help readers distinguish standard vs non-standard, and for non-standard, which other engines besides Snowflake can do it too.

**Question (i'm really asking, not for example):**
Where did EXCLUDE in `Use EXCLUDE to... exclude... columns` come from?

**Comment by ben-nour** [comment]
That's a good idea, I was thinking of putting together a reference table so I might do that.

Thanks for the feedback.

`EXCLUDE` works in Snowflake and DuckDB.
